import React, { createContext, useCallback, useContext, useEffect, useMemo, useState } from 'react';
import { useAdmin } from './AdminContext';

const LanguageContext = createContext();

const dictionaries = {
    en: {
        home: 'Home',
        services: 'Services',
        blog: 'Blog',
        contact: 'Contact',
        myQuotes: 'My Quotes',
        bookService: 'Book a Service',
        accountSettings: 'Account Settings',
        adminPanel: 'Admin Panel',
        logout: 'Logout',
        signedInAs: 'Signed in as',
        settingsTitle: 'Account Settings',
        profile: 'Profile',
        password: 'Password',
        language: 'Language',
        notifications: 'Notifications',
        profileInfo: 'Profile Information',
        email: 'Email',
        displayName: 'Display Name',
        yourName: 'Your name',
        updateProfile: 'Update Profile',
        changePassword: 'Change Password',
        newPassword: 'New Password',
        passwordHint: 'Min 6 characters',
        savePassword: 'Change Password',
        languagePreference: 'Language Preference',
        notificationPreferences: 'Notification Preferences',
        newsletter: 'Newsletter',
        newsletterHelp: 'Get cleaning tips and updates',
        quoteUpdates: 'Quote Updates',
        quoteUpdatesHelp: 'Get notified about your quotes',
        dangerZone: 'Danger Zone',
        logoutHelp: "Once you log out, you'll need to sign in again.",
        requestNewQuote: 'Request New Quote',
        quoteIntro: 'Review your quote requests and update details when needed.',
        noQuotes: 'No quotes yet',
        noQuotesHelp: 'Your quote requests will appear here after you send them.',
        getFirstQuote: 'Get Your First Quote',
        signInToQuotes: 'Sign in to see and edit your quote requests.',
        signIn: 'Sign In',
        signInToRequestQuote: 'Sign in to request a quote',
        signInToRequestQuoteHelp: 'Create or access your account so your quote request is saved under My Quotes.',
        continueToSignIn: 'Continue to Sign In',
        settingsSignInHelp: 'Please sign in to manage your profile, password, language, and notifications.',
        editQuote: 'Edit Quote',
        saveChanges: 'Save Changes',
        cancel: 'Cancel',
        selectService: 'Select a service...',
        message: 'Message',
        recentlySubmitted: 'Recently submitted',
        general: 'General',
        ourServices: 'Our Services',
        servicesIntro: 'Comprehensive cleaning solutions tailored to your needs.',
        bookNow: 'Book Now',
        needCustomPlan: 'Need a Custom Plan?',
        getFreeQuote: 'Get Free Quote',
        getYourFreeQuote: 'Get Your Free Quote',
        requestFreeQuote: 'Request Free Quote',
        contactIntro: 'Fill out the form and our team will get back to you within 24 hours.',
        professionalCleaningServices: 'Professional Cleaning Services',
        callUs: 'Call Us',
        emailUs: 'Email Us',
        visitUs: 'Visit Us',
        businessHours: 'Business Hours',
        connectWithUs: 'Connect With Us',
        quoteRequested: 'Quote Requested!',
        confirmationSent: "We've sent a confirmation to your email.",
        sendAnotherRequest: 'Send Another Request',
        fullName: 'Full Name',
        emailAddress: 'Email Address',
        phoneNumber: 'Phone Number',
        serviceType: 'Service Type',
        kindergartenCleaning: 'Kindergarten Cleaning',
        officeCleaning: 'Office Cleaning',
        residentialCleaning: 'Residential Cleaning',
        deepCleaning: 'Deep Cleaning',
        windowCleaning: 'Window Cleaning',
        yourMessage: 'Your Message',
        messagePlaceholder: 'Tell us about your cleaning needs...',
        sending: 'Sending...',
        blogTitle: 'Blog & Resources',
        blogIntro: 'Expert tips, safer spaces, and happier environments.',
        readMore: 'Read More',
        ourCleaningServices: 'Our Cleaning Services',
        servicesPreviewIntro: 'Tailored solutions for every environment.',
        learnMore: 'Learn more',
        ourSimpleProcess: 'Our Simple 4-Step Process',
        readyCleanerSpace: 'Ready for a Cleaner Space?',
        clients: 'Clients',
        happyClients: 'Happy Clients',
        rating: 'Rating',
        insured: 'Insured',
        schools: 'Schools',
        schoolsServed: 'Schools Served',
        satisfaction: 'Satisfaction',
        quickLinks: 'Quick Links',
        contactUs: 'Contact Us',
        allRightsReserved: 'All rights reserved.',
    },
    de: {
        home: 'Startseite',
        services: 'Leistungen',
        blog: 'Blog',
        contact: 'Kontakt',
        myQuotes: 'Meine Angebote',
        bookService: 'Service buchen',
        accountSettings: 'Kontoeinstellungen',
        adminPanel: 'Adminbereich',
        logout: 'Abmelden',
        signedInAs: 'Angemeldet als',
        settingsTitle: 'Kontoeinstellungen',
        profile: 'Profil',
        password: 'Passwort',
        language: 'Sprache',
        notifications: 'Benachrichtigungen',
        profileInfo: 'Profilinformationen',
        email: 'E-Mail',
        displayName: 'Anzeigename',
        yourName: 'Ihr Name',
        updateProfile: 'Profil aktualisieren',
        changePassword: 'Passwort ändern',
        newPassword: 'Neues Passwort',
        passwordHint: 'Mindestens 6 Zeichen',
        savePassword: 'Passwort ändern',
        languagePreference: 'Spracheinstellung',
        notificationPreferences: 'Benachrichtigungseinstellungen',
        newsletter: 'Newsletter',
        newsletterHelp: 'Reinigungstipps und Neuigkeiten erhalten',
        quoteUpdates: 'Angebotsupdates',
        quoteUpdatesHelp: 'Benachrichtigungen zu Ihren Angeboten erhalten',
        dangerZone: 'Abmelden',
        logoutHelp: 'Nach dem Abmelden müssen Sie sich erneut anmelden.',
        requestNewQuote: 'Neues Angebot anfragen',
        quoteIntro: 'Prüfen und bearbeiten Sie Ihre Angebotsanfragen.',
        noQuotes: 'Noch keine Angebote',
        noQuotesHelp: 'Ihre Angebotsanfragen erscheinen hier, sobald Sie sie senden.',
        getFirstQuote: 'Erstes Angebot anfragen',
        signInToQuotes: 'Melden Sie sich an, um Ihre Angebotsanfragen zu sehen und zu bearbeiten.',
        signIn: 'Anmelden',
        signInToRequestQuote: 'Melden Sie sich an, um ein Angebot anzufragen',
        signInToRequestQuoteHelp: 'Erstellen oder offnen Sie Ihr Konto, damit Ihre Anfrage unter Meine Angebote gespeichert wird.',
        continueToSignIn: 'Weiter zur Anmeldung',
        settingsSignInHelp: 'Melden Sie sich an, um Profil, Passwort, Sprache und Benachrichtigungen zu verwalten.',
        editQuote: 'Angebot bearbeiten',
        saveChanges: 'Änderungen speichern',
        cancel: 'Abbrechen',
        selectService: 'Service auswählen...',
        message: 'Nachricht',
        recentlySubmitted: 'Kürzlich gesendet',
        general: 'Allgemein',
        ourServices: 'Unsere Leistungen',
        servicesIntro: 'Umfassende Reinigungslosungen, passend zu Ihrem Bedarf.',
        bookNow: 'Jetzt buchen',
        needCustomPlan: 'Brauchen Sie einen individuellen Plan?',
        getFreeQuote: 'Kostenloses Angebot erhalten',
        getYourFreeQuote: 'Ihr kostenloses Angebot',
        requestFreeQuote: 'Kostenloses Angebot anfragen',
        contactIntro: 'Fullen Sie das Formular aus und unser Team meldet sich innerhalb von 24 Stunden.',
        professionalCleaningServices: 'Professionelle Reinigungsleistungen',
        callUs: 'Rufen Sie uns an',
        emailUs: 'Schreiben Sie uns',
        visitUs: 'Besuchen Sie uns',
        businessHours: 'Offnungszeiten',
        connectWithUs: 'Folgen Sie uns',
        quoteRequested: 'Angebot angefragt!',
        confirmationSent: 'Wir haben eine Bestatigung an Ihre E-Mail gesendet.',
        sendAnotherRequest: 'Weitere Anfrage senden',
        fullName: 'Vollstandiger Name',
        emailAddress: 'E-Mail-Adresse',
        phoneNumber: 'Telefonnummer',
        serviceType: 'Leistungsart',
        kindergartenCleaning: 'Kita-Reinigung',
        officeCleaning: 'Buroreinigung',
        residentialCleaning: 'Wohnungsreinigung',
        deepCleaning: 'Grundreinigung',
        windowCleaning: 'Fensterreinigung',
        yourMessage: 'Ihre Nachricht',
        messagePlaceholder: 'Erzahlen Sie uns von Ihrem Reinigungsbedarf...',
        sending: 'Wird gesendet...',
        blogTitle: 'Blog & Ratgeber',
        blogIntro: 'Expertentipps, sichere Raume und angenehmere Umgebungen.',
        readMore: 'Mehr lesen',
        ourCleaningServices: 'Unsere Reinigungsleistungen',
        servicesPreviewIntro: 'Passende Losungen fur jede Umgebung.',
        learnMore: 'Mehr erfahren',
        ourSimpleProcess: 'Unser einfacher 4-Schritte-Prozess',
        readyCleanerSpace: 'Bereit fur sauberere Raume?',
        clients: 'Kunden',
        happyClients: 'Zufriedene Kunden',
        rating: 'Bewertung',
        insured: 'Versichert',
        schools: 'Schulen',
        schoolsServed: 'Betreute Schulen',
        satisfaction: 'Zufriedenheit',
        quickLinks: 'Schnellzugriff',
        contactUs: 'Kontakt',
        allRightsReserved: 'Alle Rechte vorbehalten.',
    },
    fr: {
        home: 'Accueil',
        services: 'Services',
        blog: 'Blog',
        contact: 'Contact',
        myQuotes: 'Mes devis',
        bookService: 'Reserver un service',
        accountSettings: 'Parametres du compte',
        adminPanel: 'Panneau admin',
        logout: 'Deconnexion',
        signedInAs: 'Connecte en tant que',
        settingsTitle: 'Parametres du compte',
        profile: 'Profil',
        password: 'Mot de passe',
        language: 'Langue',
        notifications: 'Notifications',
        profileInfo: 'Informations du profil',
        email: 'E-mail',
        displayName: 'Nom affiche',
        yourName: 'Votre nom',
        updateProfile: 'Mettre a jour le profil',
        changePassword: 'Changer le mot de passe',
        newPassword: 'Nouveau mot de passe',
        passwordHint: 'Minimum 6 caracteres',
        savePassword: 'Changer le mot de passe',
        languagePreference: 'Preference de langue',
        notificationPreferences: 'Preferences de notification',
        newsletter: 'Newsletter',
        newsletterHelp: 'Recevoir des conseils et actualites',
        quoteUpdates: 'Mises a jour des devis',
        quoteUpdatesHelp: 'Recevoir les nouvelles de vos devis',
        dangerZone: 'Zone de sortie',
        logoutHelp: 'Apres la deconnexion, vous devrez vous reconnecter.',
        requestNewQuote: 'Demander un nouveau devis',
        quoteIntro: 'Consultez vos demandes de devis et modifiez les details si besoin.',
        noQuotes: 'Aucun devis pour le moment',
        noQuotesHelp: 'Vos demandes de devis apparaitront ici apres envoi.',
        getFirstQuote: 'Demander votre premier devis',
        signInToQuotes: 'Connectez-vous pour voir et modifier vos demandes de devis.',
        signIn: 'Se connecter',
        signInToRequestQuote: 'Connectez-vous pour demander un devis',
        signInToRequestQuoteHelp: 'Creez ou ouvrez votre compte afin que votre demande soit enregistree dans Mes devis.',
        continueToSignIn: 'Continuer vers la connexion',
        settingsSignInHelp: 'Connectez-vous pour gerer votre profil, mot de passe, langue et notifications.',
        editQuote: 'Modifier le devis',
        saveChanges: 'Enregistrer',
        cancel: 'Annuler',
        selectService: 'Choisir un service...',
        message: 'Message',
        recentlySubmitted: 'Envoye recemment',
        general: 'General',
        ourServices: 'Nos services',
        servicesIntro: 'Solutions de nettoyage completes adaptees a vos besoins.',
        bookNow: 'Reserver',
        needCustomPlan: 'Besoin d un plan sur mesure ?',
        getFreeQuote: 'Obtenir un devis gratuit',
        getYourFreeQuote: 'Obtenez votre devis gratuit',
        requestFreeQuote: 'Demander un devis gratuit',
        contactIntro: 'Remplissez le formulaire et notre equipe vous recontactera sous 24 heures.',
        professionalCleaningServices: 'Services de nettoyage professionnels',
        callUs: 'Appelez-nous',
        emailUs: 'Envoyez-nous un e-mail',
        visitUs: 'Nous trouver',
        businessHours: 'Horaires',
        connectWithUs: 'Suivez-nous',
        quoteRequested: 'Devis demande !',
        confirmationSent: 'Nous avons envoye une confirmation a votre e-mail.',
        sendAnotherRequest: 'Envoyer une autre demande',
        fullName: 'Nom complet',
        emailAddress: 'Adresse e-mail',
        phoneNumber: 'Telephone',
        serviceType: 'Type de service',
        kindergartenCleaning: 'Nettoyage de creche',
        officeCleaning: 'Nettoyage de bureaux',
        residentialCleaning: 'Nettoyage residentiel',
        deepCleaning: 'Nettoyage en profondeur',
        windowCleaning: 'Nettoyage des vitres',
        yourMessage: 'Votre message',
        messagePlaceholder: 'Parlez-nous de vos besoins de nettoyage...',
        sending: 'Envoi...',
        blogTitle: 'Blog & ressources',
        blogIntro: 'Conseils d experts, espaces plus surs et environnements plus agreables.',
        readMore: 'Lire plus',
        ourCleaningServices: 'Nos services de nettoyage',
        servicesPreviewIntro: 'Solutions adaptees a chaque environnement.',
        learnMore: 'En savoir plus',
        ourSimpleProcess: 'Notre processus simple en 4 etapes',
        readyCleanerSpace: 'Pret pour un espace plus propre ?',
        clients: 'Clients',
        happyClients: 'Clients satisfaits',
        rating: 'Note',
        insured: 'Assure',
        schools: 'Ecoles',
        schoolsServed: 'Ecoles servies',
        satisfaction: 'Satisfaction',
        quickLinks: 'Liens rapides',
        contactUs: 'Contactez-nous',
        allRightsReserved: 'Tous droits reserves.',
    },
    nl: {
        home: 'Home',
        services: 'Diensten',
        blog: 'Blog',
        contact: 'Contact',
        myQuotes: 'Mijn offertes',
        bookService: 'Dienst boeken',
        accountSettings: 'Accountinstellingen',
        adminPanel: 'Adminpaneel',
        logout: 'Uitloggen',
        signedInAs: 'Ingelogd als',
        settingsTitle: 'Accountinstellingen',
        profile: 'Profiel',
        password: 'Wachtwoord',
        language: 'Taal',
        notifications: 'Meldingen',
        profileInfo: 'Profielinformatie',
        email: 'E-mail',
        displayName: 'Weergavenaam',
        yourName: 'Uw naam',
        updateProfile: 'Profiel bijwerken',
        changePassword: 'Wachtwoord wijzigen',
        newPassword: 'Nieuw wachtwoord',
        passwordHint: 'Minimaal 6 tekens',
        savePassword: 'Wachtwoord wijzigen',
        languagePreference: 'Taalvoorkeur',
        notificationPreferences: 'Meldingsvoorkeuren',
        newsletter: 'Nieuwsbrief',
        newsletterHelp: 'Ontvang schoonmaaktips en updates',
        quoteUpdates: 'Offerte-updates',
        quoteUpdatesHelp: 'Ontvang meldingen over uw offertes',
        dangerZone: 'Uitloggen',
        logoutHelp: 'Na het uitloggen moet u opnieuw inloggen.',
        requestNewQuote: 'Nieuwe offerte aanvragen',
        quoteIntro: 'Bekijk uw offerteaanvragen en werk details bij wanneer nodig.',
        noQuotes: 'Nog geen offertes',
        noQuotesHelp: 'Uw offerteaanvragen verschijnen hier nadat u ze verstuurt.',
        getFirstQuote: 'Vraag uw eerste offerte aan',
        signInToQuotes: 'Log in om uw offerteaanvragen te bekijken en te bewerken.',
        signIn: 'Inloggen',
        settingsSignInHelp: 'Log in om uw profiel, wachtwoord, taal en meldingen te beheren.',
        editQuote: 'Offerte bewerken',
        saveChanges: 'Wijzigingen opslaan',
        cancel: 'Annuleren',
        selectService: 'Selecteer een dienst...',
        message: 'Bericht',
        recentlySubmitted: 'Onlangs verzonden',
        general: 'Algemeen',
        ourServices: 'Onze diensten',
        servicesIntro: 'Complete schoonmaakoplossingen afgestemd op uw behoeften.',
        bookNow: 'Nu boeken',
        needCustomPlan: 'Een plan op maat nodig?',
        getFreeQuote: 'Gratis offerte ontvangen',
        getYourFreeQuote: 'Vraag uw gratis offerte aan',
        requestFreeQuote: 'Gratis offerte aanvragen',
        contactIntro: 'Vul het formulier in en ons team neemt binnen 24 uur contact met u op.',
        professionalCleaningServices: 'Professionele schoonmaakdiensten',
        callUs: 'Bel ons',
        emailUs: 'Mail ons',
        visitUs: 'Bezoek ons',
        businessHours: 'Openingstijden',
        connectWithUs: 'Volg ons',
        quoteRequested: 'Offerte aangevraagd!',
        confirmationSent: 'We hebben een bevestiging naar uw e-mail gestuurd.',
        sendAnotherRequest: 'Nog een aanvraag versturen',
        fullName: 'Volledige naam',
        emailAddress: 'E-mailadres',
        phoneNumber: 'Telefoonnummer',
        serviceType: 'Soort dienst',
        kindergartenCleaning: 'Kinderopvang schoonmaak',
        officeCleaning: 'Kantoorschoonmaak',
        residentialCleaning: 'Woning schoonmaak',
        deepCleaning: 'Dieptereiniging',
        windowCleaning: 'Glasbewassing',
        yourMessage: 'Uw bericht',
        messagePlaceholder: 'Vertel ons over uw schoonmaakbehoeften...',
        sending: 'Verzenden...',
        blogTitle: 'Blog & informatie',
        blogIntro: 'Deskundige tips, veiligere ruimtes en prettigere omgevingen.',
        readMore: 'Lees meer',
        ourCleaningServices: 'Onze schoonmaakdiensten',
        servicesPreviewIntro: 'Oplossingen op maat voor elke omgeving.',
        learnMore: 'Meer informatie',
        ourSimpleProcess: 'Ons eenvoudige 4-stappenproces',
        readyCleanerSpace: 'Klaar voor een schonere ruimte?',
        clients: 'Klanten',
        happyClients: 'Tevreden klanten',
        rating: 'Beoordeling',
        insured: 'Verzekerd',
        schools: 'Scholen',
        schoolsServed: 'Scholen bediend',
        satisfaction: 'Tevredenheid',
        quickLinks: 'Snelle links',
        contactUs: 'Contact',
        allRightsReserved: 'Alle rechten voorbehouden.',
    },
};

const languageMeta = {
    en: { name: 'English', help: 'Use English as your preferred language.' },
    de: { name: 'Deutsch', help: 'Deutsch als bevorzugte Sprache verwenden.' },
    fr: { name: 'Francais', help: 'Utiliser le francais comme langue preferee.' },
    nl: { name: 'Nederlands', help: 'Gebruik Nederlands als voorkeurstaal.' },
};

export const supportedLanguages = Object.keys(languageMeta);
export const getLanguageMeta = (code) => languageMeta[code];

export const useLanguage = () => useContext(LanguageContext);

export const LanguageProvider = ({ children }) => {
    const { user } = useAdmin();
    const [language, setLanguageState] = useState(() => localStorage.getItem('languagePreference') || 'en');

    useEffect(() => {
        document.documentElement.lang = language;
        localStorage.setItem('languagePreference', language);
    }, [language]);

    useEffect(() => {
        const loadPreference = async () => {
            if (!user?.uid) return;

            try {
                const [{ doc, getDoc }, { db }] = await Promise.all([
                    import('firebase/firestore'),
                    import('../firebase/config'),
                ]);
                const userSnap = await getDoc(doc(db, 'users', user.uid));
                const storedLanguage = userSnap.data()?.languagePreference;
                if (storedLanguage && dictionaries[storedLanguage]) {
                    setLanguageState(storedLanguage);
                }
            } catch (error) {
                console.error('Error loading language preference:', error);
            }
        };

        loadPreference();
    }, [user?.uid]);

    const setLanguage = useCallback(async (value) => {
        if (!dictionaries[value]) return;

        setLanguageState(value);
        if (user?.uid) {
            const [{ doc, setDoc }, { db }] = await Promise.all([
                import('firebase/firestore'),
                import('../firebase/config'),
            ]);
            await setDoc(doc(db, 'users', user.uid), { languagePreference: value }, { merge: true });
        }
    }, [user?.uid]);

    const t = useCallback((key) => {
        return dictionaries[language]?.[key] || dictionaries.en[key] || key;
    }, [language]);

    const value = useMemo(() => ({ language, setLanguage, t }), [language, setLanguage, t]);

    return (
        <LanguageContext.Provider value={value}>
            {children}
        </LanguageContext.Provider>
    );
};
